// Generated by gencpp from file simu_visual/input_dp1.msg
// DO NOT EDIT!


#ifndef SIMU_VISUAL_MESSAGE_INPUT_DP1_H
#define SIMU_VISUAL_MESSAGE_INPUT_DP1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simu_visual
{
template <class ContainerAllocator>
struct input_dp1_
{
  typedef input_dp1_<ContainerAllocator> Type;

  input_dp1_()
    : xo(0.0)
    , yo(0.0)
    , zo(0.0)
    , xf(0.0)
    , yf(0.0)
    , zy(0.0)
    , step(0.0)
    , graficar_realtime(false)
    , idcall(0)  {
    }
  input_dp1_(const ContainerAllocator& _alloc)
    : xo(0.0)
    , yo(0.0)
    , zo(0.0)
    , xf(0.0)
    , yf(0.0)
    , zy(0.0)
    , step(0.0)
    , graficar_realtime(false)
    , idcall(0)  {
  (void)_alloc;
    }



   typedef float _xo_type;
  _xo_type xo;

   typedef float _yo_type;
  _yo_type yo;

   typedef float _zo_type;
  _zo_type zo;

   typedef float _xf_type;
  _xf_type xf;

   typedef float _yf_type;
  _yf_type yf;

   typedef float _zy_type;
  _zy_type zy;

   typedef float _step_type;
  _step_type step;

   typedef uint8_t _graficar_realtime_type;
  _graficar_realtime_type graficar_realtime;

   typedef int64_t _idcall_type;
  _idcall_type idcall;





  typedef boost::shared_ptr< ::simu_visual::input_dp1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simu_visual::input_dp1_<ContainerAllocator> const> ConstPtr;

}; // struct input_dp1_

typedef ::simu_visual::input_dp1_<std::allocator<void> > input_dp1;

typedef boost::shared_ptr< ::simu_visual::input_dp1 > input_dp1Ptr;
typedef boost::shared_ptr< ::simu_visual::input_dp1 const> input_dp1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simu_visual::input_dp1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simu_visual::input_dp1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simu_visual::input_dp1_<ContainerAllocator1> & lhs, const ::simu_visual::input_dp1_<ContainerAllocator2> & rhs)
{
  return lhs.xo == rhs.xo &&
    lhs.yo == rhs.yo &&
    lhs.zo == rhs.zo &&
    lhs.xf == rhs.xf &&
    lhs.yf == rhs.yf &&
    lhs.zy == rhs.zy &&
    lhs.step == rhs.step &&
    lhs.graficar_realtime == rhs.graficar_realtime &&
    lhs.idcall == rhs.idcall;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simu_visual::input_dp1_<ContainerAllocator1> & lhs, const ::simu_visual::input_dp1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simu_visual

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::simu_visual::input_dp1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simu_visual::input_dp1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simu_visual::input_dp1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simu_visual::input_dp1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simu_visual::input_dp1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simu_visual::input_dp1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simu_visual::input_dp1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d94a0ecc240e2dbc7926bd823ff8f394";
  }

  static const char* value(const ::simu_visual::input_dp1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd94a0ecc240e2dbcULL;
  static const uint64_t static_value2 = 0x7926bd823ff8f394ULL;
};

template<class ContainerAllocator>
struct DataType< ::simu_visual::input_dp1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simu_visual/input_dp1";
  }

  static const char* value(const ::simu_visual::input_dp1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simu_visual::input_dp1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 xo\n"
"float32 yo\n"
"float32 zo\n"
"float32 xf\n"
"float32 yf\n"
"float32 zy\n"
"float32 step\n"
"bool graficar_realtime\n"
"int64 idcall\n"
;
  }

  static const char* value(const ::simu_visual::input_dp1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simu_visual::input_dp1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xo);
      stream.next(m.yo);
      stream.next(m.zo);
      stream.next(m.xf);
      stream.next(m.yf);
      stream.next(m.zy);
      stream.next(m.step);
      stream.next(m.graficar_realtime);
      stream.next(m.idcall);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct input_dp1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simu_visual::input_dp1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simu_visual::input_dp1_<ContainerAllocator>& v)
  {
    s << indent << "xo: ";
    Printer<float>::stream(s, indent + "  ", v.xo);
    s << indent << "yo: ";
    Printer<float>::stream(s, indent + "  ", v.yo);
    s << indent << "zo: ";
    Printer<float>::stream(s, indent + "  ", v.zo);
    s << indent << "xf: ";
    Printer<float>::stream(s, indent + "  ", v.xf);
    s << indent << "yf: ";
    Printer<float>::stream(s, indent + "  ", v.yf);
    s << indent << "zy: ";
    Printer<float>::stream(s, indent + "  ", v.zy);
    s << indent << "step: ";
    Printer<float>::stream(s, indent + "  ", v.step);
    s << indent << "graficar_realtime: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.graficar_realtime);
    s << indent << "idcall: ";
    Printer<int64_t>::stream(s, indent + "  ", v.idcall);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMU_VISUAL_MESSAGE_INPUT_DP1_H
