// Generated by gencpp from file simu_visual/linear_speed_xyz.msg
// DO NOT EDIT!


#ifndef SIMU_VISUAL_MESSAGE_LINEAR_SPEED_XYZ_H
#define SIMU_VISUAL_MESSAGE_LINEAR_SPEED_XYZ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simu_visual
{
template <class ContainerAllocator>
struct linear_speed_xyz_
{
  typedef linear_speed_xyz_<ContainerAllocator> Type;

  linear_speed_xyz_()
    : xo(0.0)
    , yo(0.0)
    , zo(0.0)
    , xf(0.0)
    , yf(0.0)
    , zf(0.0)
    , vmax(0.0)
    , amax(0.0)
    , paso1(0)
    , paso2(0)
    , ls_fin(false)
    , idcall(0)
    , num_tray(0)  {
    }
  linear_speed_xyz_(const ContainerAllocator& _alloc)
    : xo(0.0)
    , yo(0.0)
    , zo(0.0)
    , xf(0.0)
    , yf(0.0)
    , zf(0.0)
    , vmax(0.0)
    , amax(0.0)
    , paso1(0)
    , paso2(0)
    , ls_fin(false)
    , idcall(0)
    , num_tray(0)  {
  (void)_alloc;
    }



   typedef float _xo_type;
  _xo_type xo;

   typedef float _yo_type;
  _yo_type yo;

   typedef float _zo_type;
  _zo_type zo;

   typedef float _xf_type;
  _xf_type xf;

   typedef float _yf_type;
  _yf_type yf;

   typedef float _zf_type;
  _zf_type zf;

   typedef float _vmax_type;
  _vmax_type vmax;

   typedef float _amax_type;
  _amax_type amax;

   typedef int64_t _paso1_type;
  _paso1_type paso1;

   typedef int64_t _paso2_type;
  _paso2_type paso2;

   typedef uint8_t _ls_fin_type;
  _ls_fin_type ls_fin;

   typedef int64_t _idcall_type;
  _idcall_type idcall;

   typedef int64_t _num_tray_type;
  _num_tray_type num_tray;





  typedef boost::shared_ptr< ::simu_visual::linear_speed_xyz_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simu_visual::linear_speed_xyz_<ContainerAllocator> const> ConstPtr;

}; // struct linear_speed_xyz_

typedef ::simu_visual::linear_speed_xyz_<std::allocator<void> > linear_speed_xyz;

typedef boost::shared_ptr< ::simu_visual::linear_speed_xyz > linear_speed_xyzPtr;
typedef boost::shared_ptr< ::simu_visual::linear_speed_xyz const> linear_speed_xyzConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simu_visual::linear_speed_xyz_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simu_visual::linear_speed_xyz_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simu_visual::linear_speed_xyz_<ContainerAllocator1> & lhs, const ::simu_visual::linear_speed_xyz_<ContainerAllocator2> & rhs)
{
  return lhs.xo == rhs.xo &&
    lhs.yo == rhs.yo &&
    lhs.zo == rhs.zo &&
    lhs.xf == rhs.xf &&
    lhs.yf == rhs.yf &&
    lhs.zf == rhs.zf &&
    lhs.vmax == rhs.vmax &&
    lhs.amax == rhs.amax &&
    lhs.paso1 == rhs.paso1 &&
    lhs.paso2 == rhs.paso2 &&
    lhs.ls_fin == rhs.ls_fin &&
    lhs.idcall == rhs.idcall &&
    lhs.num_tray == rhs.num_tray;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simu_visual::linear_speed_xyz_<ContainerAllocator1> & lhs, const ::simu_visual::linear_speed_xyz_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simu_visual

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::simu_visual::linear_speed_xyz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simu_visual::linear_speed_xyz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simu_visual::linear_speed_xyz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simu_visual::linear_speed_xyz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simu_visual::linear_speed_xyz_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simu_visual::linear_speed_xyz_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simu_visual::linear_speed_xyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "344d7938d14800189a9f18e5a9b1865b";
  }

  static const char* value(const ::simu_visual::linear_speed_xyz_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x344d7938d1480018ULL;
  static const uint64_t static_value2 = 0x9a9f18e5a9b1865bULL;
};

template<class ContainerAllocator>
struct DataType< ::simu_visual::linear_speed_xyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simu_visual/linear_speed_xyz";
  }

  static const char* value(const ::simu_visual::linear_speed_xyz_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simu_visual::linear_speed_xyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 xo\n"
"float32 yo\n"
"float32 zo\n"
"float32 xf\n"
"float32 yf\n"
"float32 zf\n"
"float32 vmax\n"
"float32 amax\n"
"int64 paso1\n"
"int64 paso2\n"
"bool ls_fin\n"
"int64 idcall\n"
"int64 num_tray\n"
;
  }

  static const char* value(const ::simu_visual::linear_speed_xyz_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simu_visual::linear_speed_xyz_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xo);
      stream.next(m.yo);
      stream.next(m.zo);
      stream.next(m.xf);
      stream.next(m.yf);
      stream.next(m.zf);
      stream.next(m.vmax);
      stream.next(m.amax);
      stream.next(m.paso1);
      stream.next(m.paso2);
      stream.next(m.ls_fin);
      stream.next(m.idcall);
      stream.next(m.num_tray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct linear_speed_xyz_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simu_visual::linear_speed_xyz_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simu_visual::linear_speed_xyz_<ContainerAllocator>& v)
  {
    s << indent << "xo: ";
    Printer<float>::stream(s, indent + "  ", v.xo);
    s << indent << "yo: ";
    Printer<float>::stream(s, indent + "  ", v.yo);
    s << indent << "zo: ";
    Printer<float>::stream(s, indent + "  ", v.zo);
    s << indent << "xf: ";
    Printer<float>::stream(s, indent + "  ", v.xf);
    s << indent << "yf: ";
    Printer<float>::stream(s, indent + "  ", v.yf);
    s << indent << "zf: ";
    Printer<float>::stream(s, indent + "  ", v.zf);
    s << indent << "vmax: ";
    Printer<float>::stream(s, indent + "  ", v.vmax);
    s << indent << "amax: ";
    Printer<float>::stream(s, indent + "  ", v.amax);
    s << indent << "paso1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.paso1);
    s << indent << "paso2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.paso2);
    s << indent << "ls_fin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ls_fin);
    s << indent << "idcall: ";
    Printer<int64_t>::stream(s, indent + "  ", v.idcall);
    s << indent << "num_tray: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num_tray);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMU_VISUAL_MESSAGE_LINEAR_SPEED_XYZ_H
