// Generated by gencpp from file simu_visual/posicionxyz.msg
// DO NOT EDIT!


#ifndef SIMU_VISUAL_MESSAGE_POSICIONXYZ_H
#define SIMU_VISUAL_MESSAGE_POSICIONXYZ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simu_visual
{
template <class ContainerAllocator>
struct posicionxyz_
{
  typedef posicionxyz_<ContainerAllocator> Type;

  posicionxyz_()
    : x0(0.0)
    , y0(0.0)
    , z0(0.0)  {
    }
  posicionxyz_(const ContainerAllocator& _alloc)
    : x0(0.0)
    , y0(0.0)
    , z0(0.0)  {
  (void)_alloc;
    }



   typedef float _x0_type;
  _x0_type x0;

   typedef float _y0_type;
  _y0_type y0;

   typedef float _z0_type;
  _z0_type z0;





  typedef boost::shared_ptr< ::simu_visual::posicionxyz_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simu_visual::posicionxyz_<ContainerAllocator> const> ConstPtr;

}; // struct posicionxyz_

typedef ::simu_visual::posicionxyz_<std::allocator<void> > posicionxyz;

typedef boost::shared_ptr< ::simu_visual::posicionxyz > posicionxyzPtr;
typedef boost::shared_ptr< ::simu_visual::posicionxyz const> posicionxyzConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simu_visual::posicionxyz_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simu_visual::posicionxyz_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simu_visual::posicionxyz_<ContainerAllocator1> & lhs, const ::simu_visual::posicionxyz_<ContainerAllocator2> & rhs)
{
  return lhs.x0 == rhs.x0 &&
    lhs.y0 == rhs.y0 &&
    lhs.z0 == rhs.z0;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simu_visual::posicionxyz_<ContainerAllocator1> & lhs, const ::simu_visual::posicionxyz_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simu_visual

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::simu_visual::posicionxyz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simu_visual::posicionxyz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simu_visual::posicionxyz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simu_visual::posicionxyz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simu_visual::posicionxyz_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simu_visual::posicionxyz_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simu_visual::posicionxyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aebe032251e0df98b17590e678288e57";
  }

  static const char* value(const ::simu_visual::posicionxyz_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaebe032251e0df98ULL;
  static const uint64_t static_value2 = 0xb17590e678288e57ULL;
};

template<class ContainerAllocator>
struct DataType< ::simu_visual::posicionxyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simu_visual/posicionxyz";
  }

  static const char* value(const ::simu_visual::posicionxyz_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simu_visual::posicionxyz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x0\n"
"float32 y0\n"
"float32 z0\n"
;
  }

  static const char* value(const ::simu_visual::posicionxyz_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simu_visual::posicionxyz_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x0);
      stream.next(m.y0);
      stream.next(m.z0);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct posicionxyz_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simu_visual::posicionxyz_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simu_visual::posicionxyz_<ContainerAllocator>& v)
  {
    s << indent << "x0: ";
    Printer<float>::stream(s, indent + "  ", v.x0);
    s << indent << "y0: ";
    Printer<float>::stream(s, indent + "  ", v.y0);
    s << indent << "z0: ";
    Printer<float>::stream(s, indent + "  ", v.z0);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMU_VISUAL_MESSAGE_POSICIONXYZ_H
