# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from simu_visual/linear_speed_xyz.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class linear_speed_xyz(genpy.Message):
  _md5sum = "344d7938d14800189a9f18e5a9b1865b"
  _type = "simu_visual/linear_speed_xyz"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 xo
float32 yo
float32 zo
float32 xf
float32 yf
float32 zf
float32 vmax
float32 amax
int64 paso1
int64 paso2
bool ls_fin
int64 idcall
int64 num_tray
"""
  __slots__ = ['xo','yo','zo','xf','yf','zf','vmax','amax','paso1','paso2','ls_fin','idcall','num_tray']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','int64','int64','bool','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       xo,yo,zo,xf,yf,zf,vmax,amax,paso1,paso2,ls_fin,idcall,num_tray

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(linear_speed_xyz, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.xo is None:
        self.xo = 0.
      if self.yo is None:
        self.yo = 0.
      if self.zo is None:
        self.zo = 0.
      if self.xf is None:
        self.xf = 0.
      if self.yf is None:
        self.yf = 0.
      if self.zf is None:
        self.zf = 0.
      if self.vmax is None:
        self.vmax = 0.
      if self.amax is None:
        self.amax = 0.
      if self.paso1 is None:
        self.paso1 = 0
      if self.paso2 is None:
        self.paso2 = 0
      if self.ls_fin is None:
        self.ls_fin = False
      if self.idcall is None:
        self.idcall = 0
      if self.num_tray is None:
        self.num_tray = 0
    else:
      self.xo = 0.
      self.yo = 0.
      self.zo = 0.
      self.xf = 0.
      self.yf = 0.
      self.zf = 0.
      self.vmax = 0.
      self.amax = 0.
      self.paso1 = 0
      self.paso2 = 0
      self.ls_fin = False
      self.idcall = 0
      self.num_tray = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8f2qB2q().pack(_x.xo, _x.yo, _x.zo, _x.xf, _x.yf, _x.zf, _x.vmax, _x.amax, _x.paso1, _x.paso2, _x.ls_fin, _x.idcall, _x.num_tray))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 65
      (_x.xo, _x.yo, _x.zo, _x.xf, _x.yf, _x.zf, _x.vmax, _x.amax, _x.paso1, _x.paso2, _x.ls_fin, _x.idcall, _x.num_tray,) = _get_struct_8f2qB2q().unpack(str[start:end])
      self.ls_fin = bool(self.ls_fin)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8f2qB2q().pack(_x.xo, _x.yo, _x.zo, _x.xf, _x.yf, _x.zf, _x.vmax, _x.amax, _x.paso1, _x.paso2, _x.ls_fin, _x.idcall, _x.num_tray))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 65
      (_x.xo, _x.yo, _x.zo, _x.xf, _x.yf, _x.zf, _x.vmax, _x.amax, _x.paso1, _x.paso2, _x.ls_fin, _x.idcall, _x.num_tray,) = _get_struct_8f2qB2q().unpack(str[start:end])
      self.ls_fin = bool(self.ls_fin)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f2qB2q = None
def _get_struct_8f2qB2q():
    global _struct_8f2qB2q
    if _struct_8f2qB2q is None:
        _struct_8f2qB2q = struct.Struct("<8f2qB2q")
    return _struct_8f2qB2q
