# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from simu_visual/parameter_ws.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class parameter_ws(genpy.Message):
  _md5sum = "13fef40ddffb08d40623ab9ab34babdd"
  _type = "simu_visual/parameter_ws"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool graficar_realtime
int64 step
int64 idcall
"""
  __slots__ = ['graficar_realtime','step','idcall']
  _slot_types = ['bool','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       graficar_realtime,step,idcall

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(parameter_ws, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.graficar_realtime is None:
        self.graficar_realtime = False
      if self.step is None:
        self.step = 0
      if self.idcall is None:
        self.idcall = 0
    else:
      self.graficar_realtime = False
      self.step = 0
      self.idcall = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2q().pack(_x.graficar_realtime, _x.step, _x.idcall))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.graficar_realtime, _x.step, _x.idcall,) = _get_struct_B2q().unpack(str[start:end])
      self.graficar_realtime = bool(self.graficar_realtime)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2q().pack(_x.graficar_realtime, _x.step, _x.idcall))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.graficar_realtime, _x.step, _x.idcall,) = _get_struct_B2q().unpack(str[start:end])
      self.graficar_realtime = bool(self.graficar_realtime)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2q = None
def _get_struct_B2q():
    global _struct_B2q
    if _struct_B2q is None:
        _struct_B2q = struct.Struct("<B2q")
    return _struct_B2q
